### PR TITLE
feat: you dont know js - chapter1

### PR DESCRIPTION
**Pull request by jellysoo97**
### You dont't know JS - Chapter 1 타입 정리

1.1 타입
1.2 내장타입
1.3 값은 타입을 가진다

### CODE REVIEW

**Review by xncbf — APPROVED** [review]

**Comment by djmin43** [comment]
good

**Review by djmin43 — APPROVED** [review]

**Comment by xncbf** [comment]
LGTM

**Comment by djmin43** [comment]
do you know chapter 1 of js now?

**Comment by djmin43** [comment]
lgtm

**Comment by jellysoo97** [comment]
> do you know chapter 1 of js now?

the answer to this question is...

스크린샷 2023-01-23 오후 11 38 33

**Pull request merged**
